/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VisualSair extends javax.swing.JFrame {
    public static Visual janela;
    
    //Ao criar a janela "JanelaSair" , já atribui a janela principal ao atributo "janela".
    public VisualSair(Visual visual) {
        initComponents();
        ManipulaTabelas manip = new ManipulaTabelas(null,this);
        manip.preencheTabelaSair(this);
        
        janela = visual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSair = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelChassi = new javax.swing.JLabel();
        textoIDSaida = new javax.swing.JTextField();
        horarioInicio = new javax.swing.JLabel();
        botaoConfirmaSaida = new javax.swing.JButton();
        botaoCancelarSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Desocupar vaga");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaSair.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificação", "Peso Máximo", "Altura Máx.", "Comprimento Máx.", "Largura Máx.", "Veículo Presente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSair.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSairMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSair);
        if (tabelaSair.getColumnModel().getColumnCount() > 0) {
            tabelaSair.getColumnModel().getColumn(0).setResizable(false);
            tabelaSair.getColumnModel().getColumn(1).setResizable(false);
            tabelaSair.getColumnModel().getColumn(2).setResizable(false);
            tabelaSair.getColumnModel().getColumn(3).setResizable(false);
            tabelaSair.getColumnModel().getColumn(4).setResizable(false);
            tabelaSair.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 965, 190));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Lista de vagas ocupadas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 985, 10));

        labelChassi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelChassi.setForeground(new java.awt.Color(255, 0, 51));
        labelChassi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelChassi.setText("Digite o ID da vaga a ser desocupada:");
        labelChassi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(labelChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, 30));

        textoIDSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoIDSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoIDSaidaKeyTyped(evt);
            }
        });
        getContentPane().add(textoIDSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 110, 30));

        horarioInicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        horarioInicio.setForeground(new java.awt.Color(51, 51, 51));
        horarioInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(horarioInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 260, 30));

        botaoConfirmaSaida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoConfirmaSaida.setText("Confimar");
        botaoConfirmaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmaSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfirmaSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 112, 30));

        botaoCancelarSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoCancelarSair.setText("Voltar");
        botaoCancelarSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarSairActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCancelarSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 140, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Restringe os textBox a receberem apenas numeros.
    private void textoIDSaidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoIDSaidaKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_textoIDSaidaKeyTyped
    
    //Ao clicar em uma linha da tabela de vagas, ja transfere o numero de ID pro respectivo textBox.
    private void tabelaSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSairMouseClicked

        DefaultTableModel model = (DefaultTableModel) tabelaSair.getModel();
        textoIDSaida.setText(model.getValueAt(tabelaSair.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tabelaSairMouseClicked

    //Fecha a janela e volta pra principal.
    private void botaoCancelarSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarSairActionPerformed
        this.setVisible(false);
        janela.setVisible(true);
    }//GEN-LAST:event_botaoCancelarSairActionPerformed
    
    //Retira o carro da vaga, registra no log, atualiza a tabela de vagas da janela principal, fecha a janela atual e reabre a principal.
    private void botaoConfirmaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmaSaidaActionPerformed
            if(textoIDSaida.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Digite o ID de uma vaga ou selecione na tabela de vagas.","Erro",JOptionPane.ERROR_MESSAGE);
            else{   
            int ID = Integer.valueOf(textoIDSaida.getText());
            boolean controle=false;
            ManipuladorDeArquivos manip2 = new ManipuladorDeArquivos();

            String aux = janela.getHorarioInicio().replace(":", "'");
            aux = aux.replace("/", " de ");
            String nomeArquivo = aux;
            int linha2=-1;
            for(int x=0;x<tabelaSair.getRowCount();x++){
                if(Integer.valueOf(tabelaSair.getValueAt(x,0).toString()) == ID){
                    controle=true;              
                    linha2=x;
                    }
            }

            if(!controle){
            JOptionPane.showMessageDialog(this,"Vaga não existe ou não está ocupada!","Erro",JOptionPane.ERROR_MESSAGE);

            try {
                    manip2.registraLog("saida","falha"," --- ",String.valueOf(ID),nomeArquivo);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,"Erro ao salvar log.","Erro",JOptionPane.ERROR_MESSAGE);
                }
            }else{
            
            Relatorio vagas = new Relatorio();
            ManipulaTabelas manip = new ManipulaTabelas(janela,null);
            vagas.getInstance();

            for(Vaga X: vagas.getListaVagas())
            {
                if(X.getID()==ID)
                    X.setDisponivel(true);
            }
            
            Veiculo carro = vagas.getCarroEstacionado(ID);
           
                try {
                    manip2.registraLog("saida","sucesso",String.valueOf(carro.getChassi()),String.valueOf(ID),nomeArquivo);
                } catch (IOException ex) {
                    Logger.getLogger(VisualSair.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            JOptionPane.showMessageDialog(this,"Veiculo "+carro.getModelo()+ " com chassi "+carro.getChassi()+ " retirado com sucesso da vaga "+ ID+"." ,"Sucesso!",JOptionPane.INFORMATION_MESSAGE);    
           
            this.dispose();
            janela.setVisible(true);
            
            int linha=0;
            int tamanho=janela.tabelaVagas.getRowCount();
            for(int x=0;x<tamanho;x++){
                if(Integer.valueOf(janela.tabelaVagas.getValueAt(x,0).toString()) == ID){
                    linha=x;   
                }
            }

            manip.liberaVaga(linha);
            }
    }
        
    }//GEN-LAST:event_botaoConfirmaSaidaActionPerformed
    
    //Volta pra janela principal.
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        janela.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualSair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VisualSair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelarSair;
    private javax.swing.JButton botaoConfirmaSaida;
    private javax.swing.JLabel horarioInicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelChassi;
    public javax.swing.JTable tabelaSair;
    private javax.swing.JTextField textoIDSaida;
    // End of variables declaration//GEN-END:variables
}
